# Code Coverage build pipeline

variables:
  EnvArtifactStem: 'environment'
  EnvFileStem: 'environment'

trigger: none

pr: none

schedules:
- cron: "30 5 * * *" # Time is UTC
  displayName: Nightly Code Coverage Build
  branches:
    include:
      - main
  always: true

jobs:
- template: templates/all-tests-job-template.yml
  parameters:
    platforms:  { Linux: ubuntu-latest }
    pyVersions: [3.8]
    testRunTypes: [ 'CodeCoverage' ]
    installationType: PipLocal
    envArtifactStem: $(EnvArtifactStem)
    envFileStem: $(EnvFileStem)

