# Simplified PyPI release pipeline

# At queue time, the user selects a Test or Production deployment. The following stages
# then run:
# - Predeployment validation (run a set of tests against the repository)
# - Creates a wheel and stores in Pipeline Artifact
# - Download wheel file from Artifact, pip install, and run tests
# - Upload the wheel to PyPI (Test or Production as specified at queue time)
# - Install from PyPI and run tests

parameters:
- name: releaseType
  displayName: Release Type
  type: string
  default: Test
  values:
  - Test
  - Production

variables:
  poolImage: "ubuntu-latest"
  poolPythonVersion: 3.6
  packageArtifactName: Wheels
  versionArtifactName: Version
  versionFileName: versionInfo.txt

trigger: none # No CI build

pr: none # Not for pull requests

# ==================================================================================================

stages:
- stage: PredeploymentValidation
  displayName: Predeployment Validation
  pool:
    vmImage: $(poolImage)

  variables:
    freezeArtifactStem: PredeployFreeze
    freezeFileStem: predeploy-requirements

  jobs:
  - template: templates/all-tests-job-template.yml
    parameters:
      platforms:  { Linux: ubuntu-latest, MacOS: macos-latest }
      installationType: 'PipLocal'
      pyVersions: [3.6.8]
      freezeArtifactStem: $(freezeArtifactStem)
      freezeFileStem: $(freezeFileStem)

# ==================================================================================================

- stage: CreateWheel
  displayName: Create Wheel Artifact
  dependsOn: PredeploymentValidation
  pool:
    vmImage: $(poolImage)

  variables:
    wheelEnvName: WheelEnvironment
    freezeArtifactName: CreateWheelFreeze
    freezeFile: createwheel-freeze.txt

  jobs:
  - job: CreateWheel
    displayName: Build and publish wheel
    pool:
      vmImage: $(poolImage)
    
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(poolPythonVersion)'
      inputs:
        versionSpec: $(poolPythonVersion)
        addToPath: true

    - template: templates/python-infra-upgrade-step-template.yml

    - template: templates/conda-setup-step-template.yml
      parameters:
        pythonVersion: 3.6.8
        pinRequirements: False
        envInfoArtifact: $(freezeArtifactName)
        envInfoFileBase: $(freezeFile)
        condaEnv: $(wheelEnvName)

    - bash: |
        source activate ${{parameters.condaEnv}}
        pip install setuptools wheel 
      displayName: 'Install setuptools'

    - script: python ./scripts/build_wheels.py --version-filename $(versionFilename) 
      displayName: 'Build wheels'

    - task: PublishPipelineArtifact@1
      displayName: "Publish wheels"
      inputs:
        path: $(System.DefaultWorkingDirectory)/dist
        artifact: $(packageArtifactName)

    - task: PublishPipelineArtifact@1
      displayName: "Publish version information file"
      inputs:
        path: '$(System.DefaultWorkingDirectory)/$(versionFilename)'
        artifact: $(versionArtifactName)